### ISSUE TITLE
[Windows] Toolkit doesn't copy itself correctly 

### ISSUE THREAD

**Issue by HastagGuigui** [Geometria-Engine/Hub#1]
Issue present in:
- 0.2.0

Steps to reproduce: 
- Create a new project
- Try to compile it
- CMD says Geometria.exe is not meant for that system 
- 😞

For those having the same issue, simply manually copy the toolkit from the hub folder to your project to fix the issue

**Comment by TheNachoBIT** [comment]
This issue has been fixed now in the latest release: https://github.com/Geometria-Engine/Hub/releases/tag/release .
Closing issue and marked as fixed c:
