### ISSUE TITLE
Hub.exe uses Linux commands on start and crashes

### ISSUE THREAD

**Issue by ghost** [Geometria-Engine/Hub#2]
Output:
```
INFO: Could not find files for the given pattern(s).
The file "where apt" doesn't exist
INFO: Could not find files for the given pattern(s).
The file "where pacman" doesn't exist
```

Issue present in:
* 0.2.42

System information:
* OS: Windows 10

Steps to reproduce:
* Launch a fresh Hub.exe from Releases

**Comment by TheNachoBIT** [comment]
Hey! Thank you for reporting this issue!

This issue has been fixed already, but i'm working on a stable patch, so i won't close this yet until i release version 0.2.43.

**Comment by TheNachoBIT** [comment]
Version 0.2.43 just released!

https://github.com/Geometria-Engine/Hub/releases/tag/v0.2.43

Feel free to test it out and let me know if your issue is fixed :D

**Comment by ghost** [comment]
Hi. Hub.exe works for me now! Thanks!
